buildCommand: |
  pip install -r requirements.txt
  python manage.py migrate --noinput
  python manage.py collectstatic --noinput
  python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username='jaseel').exists() or User.objects.create_superuser('jaseel', 'jassjaseelk@gmail.com', 'admin123')"